name: Keep API Alive

on:
    schedule:
        - cron: '0/15 * * * *'  
    workflow_dispatch:

jobs:
    cron-job:
        runs-on: ubuntu-latest
        steps:
            - name: Ping API
              timeout-minutes: 10
              run: >
                curl --fail --silent --show-error --location --retry 3 --retry-all-errors --retry-delay 30 --max-time 120 "$API_URL/api/skill"
              env:
                API_URL: https://ejmabunda-web-api-dfg5bzfbh2c8e3h5.southafricanorth-01.azurewebsites.net